apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: airbyte-abctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_FILE
              value: /metabase-data/metabase.db
          volumeMounts:
            - name: metabase-volume
              mountPath: /metabase-data
      volumes:
        - name: metabase-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: airbyte-abctl
spec:
  selector:
    app: metabase
  ports:
    - port: 3000
      targetPort: 3000
